### ISSUE TITLE
Support Trait Objects (and other unsized types)

### ISSUE THREAD

**Issue by dathinab** [alexcrichton/scoped-tls#1]
If  I'm not wrong scoped-tls could support unsized types just
fine, as it only handles references to the type, which are
sized even for unsized types.

I think it could be supported by
- changing the generic parameter `T` => `T: ?Sized`
- using `Cell(*const T)` instead of `Cell(usize)` as there might be fat pointers

And it should not bring any backward compatibility issues.

Or so I though, until I noticed, that many of the pointer methods are
not implemented for fat pointers ( e.g. prt::null, is_null, ).

While there are workarounds for this (e.g. use mem::zeroed() ),
I guess there is a good reason to not have fat pointer pointer tricks?

**Comment by dathinab** [comment]
( the simplest, but currently nighlty only work around would be to use `Option<NonZero<*const T>>` )

**Comment by alexcrichton** [comment]
Thanks for the report! Right now though the underlying OS fundamentally only gives us space for a pointer, so you'll need to pass in `&&Trait` instead of just `&Trait`. Manually opting in to the extra layer of indirection is something I'd expect consumers to do rather than force it inot the crate.
