### ISSUE TITLE
MSRV bump as a patch release breaks SemVer

### ISSUE THREAD

**Issue by mchodzikiewicz** [alexcrichton/scoped-tls#20]
Hi, you have released scoped-tls 1.0.1 bumping the MSRV and since this crate is used by `smol` that's used by `async-std`, my project built by rustc 1.58 broke after refreshing Cargo.lock. Please beware that bumping MSRV is a breaking change and should not be performed under a patch release.

IMO it would be best to yank 1.0.1 and release it as 1.1.0 instead since this might affect more people using `async-std` and older rustc versions.

BTW, you bumped MSRV it to 1.59, however I run `cargo-msrv` and it returned succeed at least for 1.31
```
$ cargo msrv
Fetching index
Determining the Minimum Supported Rust Version (MSRV) for toolchain x86_64-unknown-linux-gnu
Using check command cargo check
Check for toolchain '1.31.1-x86_64-unknown-linux-gnu' succeeded
```
I didn't have time to check lower versions.

Is there any other reason for bumping it that high?

**Comment by alexcrichton** [comment]
I would recommend updating your rustc, updating the rustc version required is not a breaking change considered by this crate.

**Comment by mchodzikiewicz** [comment]
Not a big fan of this reply - a lot of crates depend on yours - it creates a form of responsibility to the community.

This is a breaking change since what literally happened is that you pushed a new version to crates.io and it broke my code when I performed a `cargo update` and I am not even using this crate directly but via widely used `async-std`.

It would be enough just to release it as a minor version (1.1.0) instead - this is because cargo assumes patch releases are safe to bump in any circumstances - patch releases are reserved for security updates etc.

There are plenty of projects that cannot just update the rustc for many reasons - one of which might be a big formal cost of performing such an upgrade (along with an unnecessary risk of breaking critical system) as in my case.

The only mitigation for me is to opt out of default cargo policy for your create, which means I am opting out for real patch releases by setting an explicit version of your crate to `=1.0.0`, even though your crate shouldn't even be listed in my `Cargo.toml` since as I said it is only introduced by a dependency.

I assume you will not yank the version even though there are some other threads that recommend this, but please, please... at least be slightly more thoughtful for future releases since there are >23 million downloads of your crate and you can cause a headache for a lot of other developers.
