### ISSUE TITLE
Yank 1.0.1 due to breaking changes (and re-release as a v2?)

### ISSUE THREAD

**Issue by eggyal** [alexcrichton/scoped-tls#22]
In addition to #20, 1.0.1 also includes #17 which changes the public API of `ScopedKey` and breaks downstream crates (in my case, swc) that rely on that API's stability per semver guarantees.

**Comment by alexcrichton** [comment]
#20 is not a breaking change and neither is #17. The swc crate was relying on internals of this crate that are documented as not supposed to be used.

**Comment by eggyal** [comment]
Apologies, I hadn't noticed that.  Thanks for clarifying!
